### ISSUE TITLE
Infografía fases del ciclo de vida del desarrollo del software

### ISSUE THREAD

**Issue by Daisy2003lopez** [SistemasTecTlaxiaco/actividad-1-infografia-Daisy2003lopez#2]
[INFO_DOL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Daisy2003lopez/files/12482787/INFO_DOL.pdf)

**Comment by ToniDepp** [comment]
Redacción y ortografía: Un formato algo diferente 3 puntos de 3 puntos
Exposición de ideas centrales: Lo indispensable 3 puntos de 3 puntos
Organización de la información: Algo rebuscado 2 puntos de 3 puntos
Uso de imágenes y colores: Se entiende el mensaje 2.5 puntos de 3 puntos
Presentación visual: Buen diseño 2.5 puntos de 3 puntos
Referencias: No se menciona ni uno 0 puntos de 2 puntos 
Presentación: 3 puntos de 3 puntos
Calificación: 16/ 20
Calificado por: Eduardo Tomas

**Comment by josealfredo79** [comment]
Bien hecho y revisado
